### ISSUE TITLE
Adding License Information

### ISSUE THREAD

**Issue by ercanersoy** [joncampbell123/msdostest#2]
I would like to add license information of msdostest.

Thanks and best regards, Ercan

**Comment by joncampbell123** [comment]
I'll need to decide which license to apply. I'm happy to release test results for DOSBox-X vs DOSBox SVN vs DOS games as long as others don't rip off these results or fail to attribute the source of the results.

**Comment by ercanersoy** [comment]
msdostest can be licensed under MIT license.
